### ISSUE TITLE
Error origin

### ISSUE THREAD

**Issue by jneuendorf** [ianhattendorf/autocomplete-ruby#15]
Hi,

I recently often encountered the error (displayed as a notification) that's generated [here](https://github.com/ianhattendorf/autocomplete-ruby/blob/master/lib/autocomplete-ruby-client.coffee#L61-L63).
I had to search the internet to find out that this is related to this atom package.

I think it would be nice to make it easier to find the package related to an error.
Therefore I thought about creating a PR but wanted to check for the best solution first.
Two simple solutions I can think of are:
- Prepend the package name to the error message.
- In addition to the notification use `console.error` to display the error on the web console.

Which one to you prefer? Or do you have a better/different solution?

**Comment by ianhattendorf** [comment]
Sure, feel free to prepend the package name to the error messages. Is there a common format for this used in other packages? i.e. `autocomplete-ruby: exec error: ...`

`console.error` sounds like it would be helpful as well, as long as this isn't discouraged in electron apps.

**Comment by jneuendorf** [comment]
As to http://stackoverflow.com/a/6856325 console logging should not be a great concern. I am not aware of a common naming format but I guess prepending the exact package name would definitely be a good start. ;)

Therefore, I would then create a PR soon :)
