### ISSUE TITLE
Atom is become really slow

### ISSUE THREAD

**Issue by MaximeRVY** [ianhattendorf/autocomplete-ruby#20]
Hi there, 

I really like your plugin. It's really cool. 

But when I enable it, I notice a lot of lag :/ 

Is it normal ? 
How can I help to find the cause ? 

Thanks,

Maxime

**Comment by ianhattendorf** [comment]
What OS? What's your free/total memory? Are you receiving any errors/warnings from atom?

**Comment by MaximeRVY** [comment]
Hi @ianhattendorf,

Thanks for your response. 

I'm on a macbook pro , version os: 10.10.5. 

I have around 1go free on 8go total memory. 

And nop, I don't any errors/warning from atom :/ 

If I can do anything to find the cause of this problem, don't hesitate :-)

**Comment by ianhattendorf** [comment]
What model year? Depending on how large the project you're indexing is and if you have an HDD/SSD it might take a while to index at first, but that should only be at the beginning.

You could also try updating to 10.12.x, you're 2 major versions behind.

Sorry, other than that I'm not sure what it could be. I'll leave this open for a while to see if anyone else experiences any slowness or has any ideas.

**Comment by MaximeRVY** [comment]
Thanks for you response. 

The year is late 2013. And I have a SSD. 

I know my os version is pretty old :/ I'll try to do the upgrade this month.

I'll get back to you if I see any amelioration :-)

**Comment by smoothdvd** [comment]
@MaximeRDY this plugin depends rsense, it's java and really occupied too much CPU and memory.

**Comment by ianhattendorf** [comment]
I'm going to go ahead and close this, as there doesn't appear to be anything that can be done on this end.
