### ISSUE TITLE
Compatibility issue using custom path 

### ISSUE THREAD

**Issue by w3st3ry** [ianhattendorf/autocomplete-ruby#23]
Hi,

I've an error when I start my Atom using your tool.
I use rvm to manage my Ruby versions and I running on OSX.

Extract of the errors:
```
autocomplete-ruby: exec error: Error: Command failed: /Users/my_user/.rvm/gems/ruby-2.3.0/bin/rsense start --port 47367 --path /Users/my_user/GitHub/w3st3ry.github.io
env: ruby_executable_hooks: No such file or directory
```

But everything is working if I just run this command out from Atom, in my shell.

I think it's because I need to add a custom path to find my Gem. Can you fix it in `Settings` with a new entry?

Thanks in advance.

**Comment by ianhattendorf** [comment]
Are you opening atom through the launcher icon? Could you try running `atom` from the shell and see if that works?

**Comment by w3st3ry** [comment]
Yes, its works using shell instead icon.

Thanks !

**Comment by ianhattendorf** [comment]
No problem. I believe there was a workaround to this however it's been a while since I've used macOS. You could try searching for something like `osx atom path` on Google.
