### ISSUE TITLE
Throwing error in Atom IDE when I am typing any ruby keywords

### ISSUE THREAD

**Issue by vijaykumarmane** [ianhattendorf/autocomplete-ruby#24]
autocomplete-ruby: exec error: Error: Command failed: ~/.gem/ruby/2.3.0/bin/rsense stop
'~' is not recognized as an internal or external command,
operable program or batch file.

Please assist :)

**Comment by ianhattendorf** [comment]
What OS/ruby environment (rbenv/plain ruby version/etc.) are you using?

**Comment by ianhattendorf** [comment]
Closed due to inactivity.
