### ISSUE TITLE
Not work at macOS 10.12

### ISSUE THREAD

**Issue by ghost** [ianhattendorf/autocomplete-ruby#25]
I tried it several times ，but never work。
this is error information：
autocomplete-ruby: exec error: Error: Command failed: ~/.rvm/gems/ruby-2.3.3/bin/rsense start --port 47367 --path .
env: ruby_executable_hooks: No such file or directory

here is my gem env：
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.8
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Users/OSX/.rvm/gems/ruby-2.3.3
  - USER INSTALLATION DIRECTORY: /Users/OSX/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/OSX/.rvm/rubies/ruby-2.3.3/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/OSX/.rvm/gems/ruby-2.3.3/bin
  - SPEC CACHE DIRECTORY: /Users/OSX/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/OSX/.rvm/rubies/ruby-2.3.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /Users/OSX/.rvm/gems/ruby-2.3.3
     - /Users/OSX/.rvm/gems/ruby-2.3.3@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://gems.ruby-china.org"]
  - REMOTE SOURCES:
     - https://gems.ruby-china.org
  - SHELL PATH:
     - /Users/OSX/.rvm/gems/ruby-2.3.3/bin
     - /Users/OSX/.rvm/gems/ruby-2.3.3@global/bin
     - /Users/OSX/.rvm/rubies/ruby-2.3.3/bin
     - /Users/OSX/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/Wireshark.app/Contents/MacOS

I don't konw how to add rsense  to EXECUTABLE DIRECTORY. like you say at ReadMe.md :" If you need to set up the rsense path, execute gem environment: Then take the EXECUTABLE DIRECTORY, add rsense and put this into the rsense executable path."
Am i install's way not correct???  thank you very much !

**Comment by ianhattendorf** [comment]
I just released v0.2.5 which contains #19 to better detect the rsense directory. Give this version a shot and let me know the result.

**Comment by ghost** [comment]
It doesn't work. Here is error's description:
autocomplete-ruby: exec error: Error: Command failed: /Users/OSX/.rvm/gems/ruby-2.3.3/bin/rsense start --port 47367 --path /Users/OSX/Desktop/Ruby
env: ruby_executable_hooks: No such file or directory

The path of rsenes in my computer is: '/Users/OSX/.rvm/gems/ruby-2.3.3/bin/rsense'

**Comment by ianhattendorf** [comment]
This is with v0.2.5? If the auto detection fails, you'll need to set the `rsense path` config in the plugin settings to `/Users/OSX/.rvm/gems/ruby-2.3.3/bin/rsense`.

**Comment by ghost** [comment]
yeah, v2.0.5,the newest one, if I don't set the detection path, the error's description :/bin/sh: /usr/local/bin/rsense: No such file or directory

if I set the rsense path,'/Users/OSX/.rvm/gems/ruby-2.3.3/bin/rsense',  then report error like begin. 

Here is some screenshots:
<img width="801" alt="screen shot 2017-01-28 at 13 12 49" src="https://cloud.githubusercontent.com/assets/9280765/22394425/d4439fec-e55b-11e6-846e-17806e655edc.png">
<img width="704" alt="screen shot 2017-01-28 at 13 13 17" src="https://cloud.githubusercontent.com/assets/9280765/22394429/d498300c-e55b-11e6-93ff-6442e6bf4f78.png">
<img width="495" alt="screen shot 2017-01-28 at 13 13 50" src="https://cloud.githubusercontent.com/assets/9280765/22394428/d4919026-e55b-11e6-80f8-364bd529f4d1.png">
<img width="493" alt="screen shot 2017-01-28 at 13 14 18" src="https://cloud.githubusercontent.com/assets/9280765/22394427/d4916b6e-e55b-11e6-9b35-b26ac5899fd2.png">
<img width="661" alt="screen shot 2017-01-28 at 13 14 34" src="https://cloud.githubusercontent.com/assets/9280765/22394426/d48fabbc-e55b-11e6-98fe-22ed7f4d1256.png">

**Comment by ianhattendorf** [comment]
What happens if you `cd` to your project directory and run `/Users/OSX/.rvm/gems/ruby-2.3.3/bin/rsense start --port 47367 --path .`?

This looks like an RVM issue: https://stackoverflow.com/questions/18936933/bundle-update-env-ruby-executable-hooks-no-such-file-or-directory, not sure what to do about it.

**Comment by ghost** [comment]
yeah, it's RVM issue .

**Comment by ghost** [comment]
now I use this lib with manual....cry

**Comment by ghost** [comment]
close issue， thanks a lot
