### ISSUE TITLE
rsense path error

### ISSUE THREAD

**Issue by maasha** [ianhattendorf/autocomplete-ruby#26]
I get this error on my Mac:

```
autocomplete-ruby: exec error: Error: Command failed: ~/.gem/ruby/2.3.0/bin/rsense start --port 47367 --path /Users/maasha/scratch/simple-todos
/bin/sh: /Users/maasha/.gem/ruby/2.3.0/bin/rsense: No such file or directory
```

I installed rsense with `gem install rsense` and it is located here:

```
$ which rsense
/usr/local/bin/rsense
```

**Comment by ianhattendorf** [comment]
I just released v0.2.5 which should be able to detect the rsense path in more scenarios (thanks to #19). If it still doesn't work after this, you can manually set the rsense path in the plugin config (see readme).

**Comment by maasha** [comment]
Installed the upgrade and restarted Atom. Issues gone, yay! Good job!

**Comment by ianhattendorf** [comment]
Good to hear! Credit to @chenasraf
