### ISSUE TITLE
Uncaught TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by genellern** [ianhattendorf/autocomplete-ruby#27]
[Enter steps to reproduce:]

1. Brand new installation of Atom
2. Click on install autocomplete-ruby package.

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.9.5
**Thrown From**: [autocomplete-ruby](https://github.com/ianhattendorf/autocomplete-ruby) package 0.2.5

### Stack Trace

Uncaught TypeError: Cannot read property 'join' of undefined

```
At /Users/genellern/.atom/packages/autocomplete-ruby/lib/autocomplete-ruby-client.coffee:30

TypeError: Cannot read property 'join' of undefined
    at /packages/autocomplete-ruby/lib/autocomplete-ruby-client.coffee:30:24
    at Function.grep (/packages/autocomplete-ruby/node_modules/jquery/dist/jquery.js:438:23)
    at /packages/autocomplete-ruby/lib/autocomplete-ruby-client.coffee:29:30
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
  5x -9:44.5.0 core:close (input.hidden-input)
     -8:04.3.0 core:move-left (input.hidden-input)
 12x -8:03.4.0 core:backspace (input.hidden-input)
  2x -4:48.7.0 core:confirm (input.hidden-input)
  4x -4:38.4.0 core:backspace (input.hidden-input)
  3x -4:01.7.0 core:move-left (input.hidden-input)
  6x -4:00.9.0 core:backspace (input.hidden-input)
     -3:59.9.0 core:confirm (input.hidden-input)
     -2:38.4.0 find-and-replace:show (div.panels-item)
     -2:36.2.0 core:confirm (input.hidden-input)
     -2:35.5.0 editor:consolidate-selections (input.hidden-input)
     -2:35.5.0 core:cancel (input.hidden-input)
  3x -1:48.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.21.0 
atom-bootstrap3 1.2.12 
autocomplete-ruby 0.2.5 
data-atom 0.24.1 
hyperclick 0.0.40 
php-cs-fixer 4.1.0 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.2.0 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.1 
php-integrator-tooltips 1.1.5 
```

**Comment by ianhattendorf** [comment]
Does this happen more than once? Or just on initial install? I've never seen this before, and I don't know why `process.CMD` would be null...

https://github.com/ianhattendorf/autocomplete-ruby/blob/master/lib/autocomplete-ruby-client.coffee#L30

@Mexxerio any ideas?

**Comment by genellern** [comment]
I couldn't install the package, every time I tried I got the error.
Is there any dependencies to meet? Like a specific version of ruby?

**Comment by ianhattendorf** [comment]
That's odd. You click install, get that error, and the package doesn't show up in your list of packages after?

What OS/ruby version are you using? And did you install rsense (see the readme)?

**Comment by genellern** [comment]
I get the error message and it takes me back to the packages list, the package is not installed.

OS: Sierra
Ruby: ruby 2.0.0p64

**Comment by ianhattendorf** [comment]
Hmm, I'm able to install it on Windows 10 & Linux (Arch) fine. Unfortunately I don't have a mac to test on. 

Could you try installing via the terminal? `apm install autocomplete-ruby`.

If that doesn't work, you could try making a backup of your atom config/packages and starting from scratch, uninstalling and only installing this package.

Also make sure you have the `rsense` gem installed, you might need to set it's path in the plugin preferences.

**Comment by ianhattendorf** [comment]
Closed due to no response.
