### ISSUE TITLE
Can't find rsense when using rvm or rbenv

### ISSUE THREAD

**Issue by eprislac** [ianhattendorf/autocomplete-ruby#28]
The plugin has no idea where to look for the rsense gem under rvm or rbenv

**Comment by eprislac** [comment]
Under rvm `which rsense` gives this: `/Users/<my_username>/.rbenv/shims/rsense`.

**Comment by ianhattendorf** [comment]
Did you read the readme and try setting the Rsense Path config setting?

**Comment by ianhattendorf** [comment]
Closed due to no response.
