### ISSUE TITLE
Unable to start rsense on osx yosemite

### ISSUE THREAD

**Issue by lulu-2021** [ianhattendorf/autocomplete-ruby#3]
I have autocomplete-plus installed and autocomplete-ruby. I have installed rsense via Gemfile - I am using rvm and gemsets for the project.

Regardless of whether I start with specifiying the port and the project folder or not - the response is the same and the service does not respond to testing with curl - i.e. it is not started correctly and hence autocomplete-ruby cannot talk to the server.

Any ideas would be welcome - THANKS

The rsense start command produces this in the /tmp/rsense.log

materialize at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/spec_set.rb:92
             map! at org/jruby/RubyArray.java:2444
      materialize at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/spec_set.rb:85
            specs at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/definition.rb:133
        specs_for at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/definition.rb:178
  requested_specs at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/definition.rb:167
  requested_specs at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/environment.rb:18
            setup at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/runtime.rb:13
            setup at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler.rb:120
           (root) at /Users/steveforkin/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/setup.rb:17
          require at org/jruby/RubyKernel.java:1071
           (root) at /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/jruby-jars-1.7.18/lib/jruby-stdlib-1.7.18.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1

**Comment by ianhattendorf** [comment]
Just to be sure, you ran `bundle install` followed by `bundle exec rsense`?

**Comment by lulu-2021** [comment]
Yep… :)

**Comment by ianhattendorf** [comment]
Hmm, not sure why it wouldn't work. Maybe try installing it globally: `gem install rsense` and `rsense start` and see what happens?

**Comment by ianhattendorf** [comment]
This looks to be an issue with rsense, closing for now.
