### ISSUE TITLE
autocomplete-ruby brings up a ton of errors when using a templating language like ERB

### ISSUE THREAD

**Issue by BigDaddyDeadpoo1** [ianhattendorf/autocomplete-ruby#33]
It's brings up a BUNCH of "Error stopping rsense" error popups. Totally understand if consideration of  templating languages hasn't been integrated into this package. I doubt it's easy and I am definitely not mad about it at all. Just letting you all know.

**Comment by ianhattendorf** [comment]
That's interesting, what's the extension of the ERB files? `.html.erb`? `.erb.html`? The only selector we target is `.source.ruby`, and ERB should be ignored as it's `text.html.erb` AFAIK...

Could you create a small reproducible project on github so I can take a look?

**Comment by ianhattendorf** [comment]
Closing, no response.
