### ISSUE TITLE
Unable to start Rsense from Atom

### ISSUE THREAD

**Issue by BrennickL** [ianhattendorf/autocomplete-ruby#37]
autocomplete-ruby: exec error: Error: Command failed: C:/RailsInstaller/Ruby2.3.0/bin/rsense start --port 47367 --path C:\Sites
C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/lib/rsense/client/runner.rb:112:in `start': uninitialized constant Spoon::FileActions (NameError)
Did you mean?  FileUtils
	from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:12:in `<top (required)>'
	from C:/RailsInstaller/Ruby2.3.0/bin/rsense:22:in `load'
	from C:/RailsInstaller/Ruby2.3.0/bin/rsense:22:in `<main>'

(You might need to set the rsense path, see the readme)

This is my current Rsense Pathway: C:/RailsInstaller/Ruby2.3.0/bin/rsense which is the default pathway. It was checked and rsense executable is there, just non-responsive...

**Comment by ianhattendorf** [comment]
Unfortunately, [RSense](https://github.com/rsense/rsense) (what this plugin relies on to provide autocompletion) isn't working on windows (see `Known Issues` in the Readme), and hasn't been actively developer for a few years now.

I'll add a bigger warning in the Readme regarding the current status of Windows support.
