### ISSUE TITLE
Rsense can not start on OSX

### ISSUE THREAD

**Issue by mrkaspa** [ianhattendorf/autocomplete-ruby#40]
I use ruby 2.4.1 and rvm

autocomplete-ruby: exec error: Error: Command failed: rsense start --port 47367 --path /Users/mrkaspa/code/rs/rsdemo
/Users/mrkaspa/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem rsense (>= 0.a) (Gem::GemNotFoundException)
	from /Users/mrkaspa/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/mrkaspa/.rvm/gems/ruby-2.4.1/bin/rsense:23:in `<main>'
	from /Users/mrkaspa/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mrkaspa/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
(You might need to set the rsense path, see the readme)

**Comment by ianhattendorf** [comment]
What happens when you execute `which rsense`? Did you look at the readme regarding setting the rsense path?

**Comment by mrkaspa** [comment]
I got this /Users/mrkaspa/.rvm/gems/ruby-2.4.1/bin/rsense and in the atom conf I have this /Users/mrkaspa/.rvm/rubies/ruby-2.4.1/bin/rsense but in that path I have

```
ls .rvm/rubies/ruby-2.4.1/bin/
erb  gem  irb  rake rdoc ri   ruby
```

**Comment by mrkaspa** [comment]
It's weird but now it works
