### ISSUE TITLE
Autocomplete not working (rsense throwing net::ERR_CONNECTION_REFUSED errors)

### ISSUE THREAD

**Issue by saadq** [ianhattendorf/autocomplete-ruby#42]
As I type code in my editor, no autocompletion happens and errors like these show up in the console:

<img width="1440" alt="screen shot 2017-07-20 at 4 46 23 pm" src="https://user-images.githubusercontent.com/5678694/28438157-2b53dd3c-6d6b-11e7-9892-4890990c1caa.png">

`which rsense` gives the same path that is being used in the config for `autocomplete-ruby`: `/Users/squadri/.rvm/gems/ruby-2.4.1/bin/rsense`

My Ruby version: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`

Let me know if I could provide any other details.

**Comment by ianhattendorf** [comment]
The plugin isn't able to talk with the rsense server. Can you check to see if it's running when this error occurs?

**Comment by saadq** [comment]
Admittedly, I know very little about the Ruby ecosystem. Do you mean to just run `rsense start` and then open Atom? I tried doing that, but the errors still seem to happen.

**Comment by ianhattendorf** [comment]
The RSense server is a separate process. Try the following:

- close all atom windows
- kill all currently running rsense processes (`killall rsense`)
- launch atom
- open a `.rb` file
- wait a few seconds
- check if autocompletion is working
- if not, check if rsense is running (`ps aux | grep rsense`)

**Comment by saadq** [comment]
Hmm, the errors are still there.

![screen shot 2017-07-20 at 6 09 06 pm](https://user-images.githubusercontent.com/5678694/28440981-90afba56-6d76-11e7-897a-03312b8b37ea.png)

![screen shot 2017-07-20 at 6 05 44 pm](https://user-images.githubusercontent.com/5678694/28440855-1765f9b2-6d76-11e7-9876-87622f62fca3.png)

**Comment by saadq** [comment]
Although something kinda strange is happening.

![screen shot 2017-07-20 at 6 10 48 pm](https://user-images.githubusercontent.com/5678694/28441036-cb549a78-6d76-11e7-8fba-71b6d5aea984.png)

If I manually run `rsense start`, I'm not sure why the process isn't found when I try to kill it. Is it immediately stopping?

**Comment by ianhattendorf** [comment]
Looks like either rsense is crashing or never starting, have you looked at the logs at `/tmp/rsense.log`?

**Comment by saadq** [comment]
Yup, there are some errors in there that I will need to fix, looks like a few missing gems for some reason.

Anyways, I'm guessing this isn't an issue with your package. Thanks for your help with debugging!

**Comment by sanchit121** [comment]
Hi, Anyone found the solution, I m also facing same. Please help

**Comment by JonnyCBB** [comment]
I'm facing the same issue. I've tried the steps above and nothing has helped.
