### ISSUE TITLE
Error when running 'rsense start'

### ISSUE THREAD

**Issue by AndrewHartAR** [ianhattendorf/autocomplete-ruby#6]
I followed the instructions to install this properly. When I run rsense start from my project's directory, I get this error:

> /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found (LoadError)

**Comment by ianhattendorf** [comment]
[RSense](https://github.com/rsense/rsense) is a separate program which this plugin uses to get code completion information.

I googled the error message and found this: https://github.com/ffi/ffi/issues/461 which seems to be an issue with OS X El Capitan, is that what you're running?

Anyway, rsense appears to be dead so I don't see this getting fixed anytime soon.
